### ISSUE TITLE
James fails to lookup images

### ISSUE THREAD

**Issue by MCOfficer** [MCOfficer/EndlessSky-Discord-Bot#110]
```java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at de.btobastian.sdcf4j.handler.JDA3Handler.invokeMethod(JDA3Handler.java:146)
        at de.btobastian.sdcf4j.handler.JDA3Handler.handleMessageCreate(JDA3Handler.java:130)
        at de.btobastian.sdcf4j.handler.JDA3Handler.access$000(JDA3Handler.java:39)
        at de.btobastian.sdcf4j.handler.JDA3Handler$1.onMessageReceived(JDA3Handler.java:55)
        at net.dv8tion.jda.core.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:406)
        at net.dv8tion.jda.core.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:84)
        at net.dv8tion.jda.core.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:122)
        at net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:37)
        at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:990)
        at net.dv8tion.jda.core.requests.WebSocketClient.onTextMessage(WebSocketClient.java:664)
        at net.dv8tion.jda.core.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1038)
        at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:368)
        at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:270)
        at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:990)
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:749)
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
Caused by: java.lang.IllegalStateException: Cannot build a message without content!
        at net.dv8tion.jda.core.requests.restaction.MessageAction.finalizeData(MessageAction.java:600)
        at net.dv8tion.jda.core.requests.RestAction.queue(RestAction.java:278)
        at net.dv8tion.jda.core.requests.RestAction.queue(RestAction.java:244)
        at bot.LookupCommands.PrintImage(LookupCommands.java:436)
        at bot.LookupCommands.onShowimageCommand(LookupCommands.java:261)
        ... 22 common frames omitted```

**Comment by MCOfficer** [comment]
49d1907a9997fcb3ee5f4a5d7a015d7a37f8359f
